# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - aula-virtual-backend

on:
  push:
    branches:
      - backend-despliegue
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
      
      - name: Debug - List all files in root
        run: |
          echo "=== Current directory ==="
          pwd
          echo "=== All files and directories ==="
          ls -la
          echo "=== Looking for requirements.txt specifically ==="
          find . -name "requirements.txt" -type f
          echo "=== Contents of any requirements.txt found ==="
          if [ -f requirements.txt ]; then
            echo "Found requirements.txt in root:"
            cat requirements.txt
          else
            echo "No requirements.txt found in root"
          fi

      - name: Install dependencies
        run: |
          source venv/bin/activate
          pip install -r requirements.txt
      
      - name: Zip artifact for deployment
        run: zip -r release.zip . -x "venv/*" "__pycache__/*" "*.pyc" ".git/*" ".github/*"

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_88620433B40947AEBBBE4D4C487AB13B }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_FFF3BD83F5B148E8BAD277EC9F7CE9EF }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_1FAF6BE01A444D4A87FB1C64D24EBBE3 }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'aula-virtual-backend'
          slot-name: 'Production'
