# Generated by Django 5.2.1 on 2025-06-09 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('presente', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleMateria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('primaria', 'Primaria'), ('secundaria', 'Secundaria')], max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroAsistenciaMovil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('ubicacion_lat', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('ubicacion_lng', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
            ],
            options={
                'verbose_name': 'Registro de Asistencia Móvil',
                'verbose_name_plural': 'Registros de Asistencia Móvil',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='SesionAsistenciaMovil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código único de 6 dígitos', max_length=6, unique=True)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin', models.DateTimeField(help_text='Cuando expira la sesión')),
                ('activa', models.BooleanField(default=True)),
                ('duracion_minutos', models.IntegerField(default=15, help_text='Duración en minutos')),
                ('total_registros', models.IntegerField(default=0, help_text='Cuántos estudiantes se registraron')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Sesión de Asistencia Móvil',
                'verbose_name_plural': 'Sesiones de Asistencia Móvil',
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
