# Generated by Django 5.2.1 on 2025-06-09 04:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actividad', '0003_initial'),
        ('curso', '0001_initial'),
        ('materia', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='detallemateria',
            name='actividad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detalles_materia', to='actividad.actividad'),
        ),
        migrations.AddField(
            model_name='detallemateria',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_materia', to='curso.curso'),
        ),
        migrations.AddField(
            model_name='detallemateria',
            name='profesor',
            field=models.ForeignKey(help_text='Profesor asignado a la materia', on_delete=django.db.models.deletion.CASCADE, related_name='detalles_materia', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='detalle_materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='materia.detallemateria'),
        ),
        migrations.AddField(
            model_name='detallemateria',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_materia', to='materia.materia'),
        ),
        migrations.AddField(
            model_name='materia',
            name='nivel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materias', to='materia.nivel'),
        ),
        migrations.AddField(
            model_name='registroasistenciamovil',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_movil', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sesionasistenciamovil',
            name='detalle_materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones_movil', to='materia.detallemateria'),
        ),
        migrations.AddField(
            model_name='registroasistenciamovil',
            name='sesion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='materia.sesionasistenciamovil'),
        ),
        migrations.AlterUniqueTogether(
            name='registroasistenciamovil',
            unique_together={('sesion', 'estudiante')},
        ),
    ]
